name: Build & Test CI

on: 
  push: 
    branches: 
      - master
  pull_request: 
    branches: 
      - master

jobs: 
  job1: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.ADMIN_TOKEN }}
      - name: Add NPM & Github Credentials
        run:
          npm config set always-auth true
          npm config set //npm.pkg.github.com/:_authToken ${{ secrets.GH_PACKAGE_TOKEN }}   
          npm config set @BlackWind57:ds.e https://npm.pkg.github.com
          npm set email blackwind757@gmail.com
          git config user.email "blackwind757@gmail.com"
          git config user.name "Black Wind"
      - name: Checkout git and pull branch
        run:
          echo $GITHUB_HEAD_REF
          git checkout $GITHUB_HEAD_REF && git pull
      - name: Install dependencies
        run: yarn
      - name: Build Packages
        run: yarn build
      - name: Running Automated Tests
        run: yarn test
      - name: Running Visual Regression Test
        env: 
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        run: yarn test:chromatic
      - name: Publishing to Github Package
        run: yarn run publish