name: Build & Test CI

on: 
  push: 
    branches: 
      - master
  pull_request: 
    branches: 
      - master

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.ADMIN_TOKEN }}
      - name: Install Yarn
        run: npm install -g yarn
      - name: Add NPM & Github Credentials
        run:
          npm config set always-auth true
          npm config set //npm.pkg.github.com/:_authToken ${{ secrets.GH_PACKAGE_TOKEN }}   
          npm config set @BlackWind57:registry https://npm.pkg.github.com
          npm set email blackwind757@gmail.com
          git config --global user.email "cristo1494@yahoo.com"
          git config --global user.name "Darryl"
          git config --list
          git fetch
          cat .gitconfig
      - name: Install dependencies
        run: yarn
      - name: Build Packages
        run: yarn build
      - name: Running Automated Tests
        run: yarn test
      - name: Running Visual Regression Test
        env: 
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        run: yarn test:chromatic
      - name: Publishing to Github Package
        run:
          git config --list && yarn run publish