name: Build & Test CI

on: 
  push: 
    branches: 
      - master
  pull_request: 
    branches: 
      - master

jobs: 
  job1: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: yarn
      - name: Build Packages
        run: yarn build
      - name: Running Automated Tests
        run: yarn test
      - name: Running Visual Regression Test
        env: 
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        run: 
          yarn test:chromatic