name: Build & Test CI

on: 
  push: 
    branches: 
      - master
  pull_request: 
    branches: 
      - master

jobs: 
  job1: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Build Packages
        run: yarn build
      - name: Running Automated Tests
        run: yarn test